# Standard EDMD regressor without regularization.
#
# This config specifies a regressor that is directly instantiated by Hydra. It
# is roughly equivalent to the following code::
#
#     pykoop.Edmd(alpha=0)
#
# Details: https://hydra.cc/docs/advanced/instantiate_objects/overview/

regressor:
  _target_: pykoop.Edmd
  alpha: 0
