defaults:
  - /regressor@regressor.hinf_regressor: iter_regressor_base

regressor:
  _target_: pykoop.lmi_regressors.LmiHinfZpkMeta
  hinf_regressor:
    _target_: pykoop.lmi_regressors.LmiDmdcHinfReg
    alpha: 1
    ratio: 1
    tsvd_unshifted:
      _target_: pykoop.Tsvd
      truncation: 'economy'
    tsvd_shifted:
      _target_: pykoop.Tsvd
      truncation: 'unknown_noise'
    iter_atol: 1e-12  # Force 20 iterations
    max_iter: 20  # Force 20 iterations
  type: post
  zeros: -0.0
  poles: -0.1
  gain: 1.0
  discretization: bilinear
  t_step: -1
  units: normalized