defaults:
  - /regressor: iter_regressor_base

regressor:
  _target_: pykoop.lmi_regressors.LmiDmdcHinfReg
  alpha: 1
  ratio: 1
  tsvd_unshifted:
    _target_: pykoop.Tsvd
    truncation: 'economy'
  tsvd_shifted:
    _target_: pykoop.Tsvd
    truncation: 'unknown_noise'
