# Base configuration for all iterative regressors (i.e., ones that solve
# bilinear matrix inequalities).

# Maximum number of iterations
max_iter: 100

# Tolerance for strict of LMI constraints
picos_eps: 1e-5

# Absolute tolerance for objective cost change. Iteration stops when the change
# in objectiv function is less than this value.
iter_atol: 1e-6

# Parameters for the SDP solver. Sets solver (MOSEK), dualization, verbosity,
# number of threads, and solver tolerances for feasibility and optimality.
solver_params:
  solver: 'mosek'
  dualize: True
  verbosity: 0
  mosek_params:
    MSK_IPAR_NUM_THREADS: 16
  '*_fsb_tol': 1e-6
  '*_opt_tol': 1e-6
